openapi: 3.1.0
info:
  title: Inventory API
  version: 1.0.0

tags:
  - name: Items
    description: Item management
  - name: Stock
    description: Stock operations

paths:
  /items:
    get:
      tags:
        - Items
      summary: List items

  /items/{sku}:
    get:
      tags:
        - Items
      summary: Get item

  /items/{sku}/stock-adjustments:
    post:
      tags:
        - Stock
      summary: Adjust stock
