openapi: 3.1.0
info:
  title: Inventory API
  version: 1.0.0

tags:
  - name: Items
    description: Item management
  - name: Stock
    description: Stock operations

paths:
  /items:
    get:
      tags: [Items]
      operationId: listItems
      summary: List items
      responses:
        "200":
          description: OK

  /items/{sku}/stock-adjustments:
    post:
      tags: [Stock]
      operationId: adjustStock
      summary: Adjust stock
      parameters:
        - name: sku
          in: path
          required: true
          schema: { type: string }
      responses:
        "200":
          description: OK
